spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eatsattva
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create | update | validate | none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: INFO

rsa:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem